### ISSUE TITLE
Some application is missing...

### ISSUE THREAD

**Issue by rafaelcamaradev** [juniorsaraviao/EcommerceApp#1]
Hi,

When you clone the project and try to load (Android and iOS) this message appears: 

For Android:
"Ecommerce\Ecommerce.Android\Ecommerce.Android.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=EFBA0AD7-5A72-4C68-AF49-83D382785DCF"

For iOS:
"Ecommerce\Ecommerce.iOS\Ecommerce.iOS.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=FEACFBD2-3405-455C-9665-78FE426C6842"

**Comment by juniorsaraviao** [comment]
Please, verify if you have installed Xamarin in VS.
![xamarin](https://user-images.githubusercontent.com/43689290/112645914-fc668780-8e14-11eb-8cb5-618812fffb38.png)

**Comment by rafaelcamaradev** [comment]
Yes, i have it

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Junior Saravia ***@***.***>
Enviado: Friday, March 26, 2021 11:24:46 AM
Para: juniorsaraviao/EcommerceApp ***@***.***>
Cc: rafaelcamaradev ***@***.***>; Author ***@***.***>
Assunto: Re: [juniorsaraviao/EcommerceApp] Some application is missing... (#1)


Please, verify if you have installed Xamarin in VS.
[xamarin]<https://user-images.githubusercontent.com/43689290/112645914-fc668780-8e14-11eb-8cb5-618812fffb38.png>

**Comment by juniorsaraviao** [comment]
That's weird. Verify your Android or iOS sdk instead.

![imagen](https://user-images.githubusercontent.com/43689290/112676510-84a95480-8e36-11eb-8456-a4ac9d4fc4e1.png)

**Comment by rafaelcamaradev** [comment]
Already did that . I uninstalled and installed two different SDKs .. nothing

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Junior Saravia ***@***.***>
Enviado: Friday, March 26, 2021 3:24:49 PM
Para: juniorsaraviao/EcommerceApp ***@***.***>
Cc: rafaelcamaradev ***@***.***>; Author ***@***.***>
Assunto: Re: [juniorsaraviao/EcommerceApp] Some application is missing... (#1)


That's weird. Verify your Android or iOS sdk instead.

[imagen]<https://user-images.githubusercontent.com/43689290/112676510-84a95480-8e36-11eb-8456-a4ac9d4fc4e1.png>

**Comment by juniorsaraviao** [comment]
Well, I'm not sure what's going on because I'm working with xamarin on my computer and it's working fine. 
Try this [link](https://docs.microsoft.com/en-us/answers/questions/90099/the-application-which-this-project-type-is-based-o.html)
